export interface AccessGroupUser {
    
    id?: string; // generated by Firestore if not set on saving
    name: string;
    description: string;
    createdAt: Date;
    updatedAt: Date;
    users: string[]; // assigned users to group
  }