import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReactQueryProvider from "./utils/providers/ReactQueryProvider";
import Header from "./header";
import Sidebar from "./sidebar";
import { AuthProvider } from "./context/auth-context"; // Import AuthProvider to manage user authentication

// Defining local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          {" "}
          {/* Wrapping the application with AuthProvider to manage authentication state globally */}
          <div className="flex flex-col h-screen">
            <Header /> {/* Application header */}
            {/* Main content area with sidebar */}
            <div className="flex flex-grow">
              <Sidebar /> {/* Sidebar for navigation */}
              <main className="flex-grow p-8">{children}</main> {/* Main content */}
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
